# Definition of the Conda Development Environment.
#
# WARNING: INTEL MKL is not open source.
# WARNING: Only tested on Linux with x86/x64.
# WARNING: Only tested with PostgreSQL 14.13.
# WARNING: Only tested with Miniforge 24.7.1.
# WARNING: Only tested with Python 3.10.
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: pyfreecoil
channels: [conda-forge]
dependencies:
  # base installation
  - python=3.10
  # pypeec solver
  - pypeec=5.2.4
  # dev tools
  - pip=24.2
  - pkg-config=0.29.2
  - python-build=1.2.2
  # logging and serialization
  - scilogger=1.2.0
  - scisave=1.4.0
  - jsonschema=4.23.0
  - colorama=0.4.0
  # numerical libraries
  - numpy=1.26.4
  - scipy=1.13.1
  - joblib=1.4.2
  # geometry libraries
  - vtk=9.2.6
  - pyvista=0.40.0
  - shapely=2.0.1
  - rasterio=1.3.8
  - pillow=10.0.0
  - cadquery=2.4.0
  # plotting libraries
  - pyqt=5.15.7
  - pyvistaqt=0.11.0
  - matplotlib=3.7.1
  # numerical libraries
  - pyamg=5.0.1
  - scikit-umfpack=0.3.3
  - mkl-devel=2023.2.0
  # database libraries
  - pandas=2.1.3
  - psycopg2=2.9.7
  # optimizer libraries
  - pygad=3.2.0
  - optuna=3.4.0
  - cmaes=0.11.1
  # install from PyPi
  - pip:
    # FFT library (conda package is not multithreaded)
    - pyFFTW==0.13.1
    # PARDISO solver library (conda package is partially broken)
    - pydiso==0.0.5
    # optimizer library (conda package is outdated)
    - nevergrad==1.0.5
    # GERBER library (conda package is not available)
    - gerber-writer==0.4.3.3
