# Parameters for encoding/decoding inductor designs into variable vectors.
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

# bounds for scaling the coordinates of the nodes
"x_min": -0.5e-3
"x_max": +0.5e-3
"y_min": -0.5e-3
"y_max": +0.5e-3

# bounds for scaling the trace widths
"width_min": 80.0e-6
"width_max": 380.0e-6

# bounds for encoding the continuous variables
"norm_min": 0.0
"norm_max": 1.0

# size of the encoding designs (resample if required)
"n_wdg": !sub "N_WDG"

# list of layers used for the traces
"layer_list": !sub "LAYER_LIST"

# size of the (partially or totally) constrained terminals (source and sink)
"n_add_src": !sub "N_ADD_SRC"
"n_add_sink": !sub "N_ADD_SINK"

# position of the (partially or totally) constrained terminals (source and sink)
#   - specify the node coordinates, the trace widths, and the layers
#   - the dimension of the elements should match the aforementioned terminal sizes
"src_geom": !sub "SRC_GEOM"
"sink_geom": !sub "SINK_GEOM"

# number of nodes and traces that can be located outside the specified component outline
#   - can be used for both the source and the sink terminals
#   - this is used to have fixed terminals located outside the outline
"n_mask_src": !sub "N_MASK_SRC"
"n_mask_sink": !sub "N_MASK_SINK"
