# Configuration for the CAD export.
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

# scaling factor (scaling for mm units)
"scaling": 1.0e+3

# tolerance for the STL files
"tolerance": 1.0e-3

# layer stack description (layer name and layer indices)
"stack_dict":
    "bot": [[0]]
    "top": [[4]]
    "mid": [[2]]
    "via": [[1], [3], [1, 2, 3]]
